services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  HDNET\CalendarizeContent\:
    resource: '../Classes/*'

  HDNET\CalendarizeContent\EventListener\IndexRepositorySearchListener:
    tags:
      - name: event.listener
        identifier: 'calendarizeContentSearch'
        event: HDNET\Calendarize\Event\IndexRepositoryFindBySearchEvent

  HDNET\CalendarizeContent\EventListener\ContentEventConstraintsListener:
    tags:
      - name: event.listener
        identifier: 'contentEventConstraints'
        event: HDNET\Calendarize\Event\IndexRepositoryDefaultConstraintEvent
